### PR TITLE
Dont subtract left offset twice

### PR DESCRIPTION
**Pull request by arski**
@udemy/team-t the left offset is already subtracted in https://github.com/udemy/videojs-sneakpeek/compare/fix/offset-left?expand=1#diff-f87aa5382c24a864d96180e37482b145R202 - don't do it twice

### CODE REVIEW

**Comment by arski** [comment]
Fixes incorrect seeking time resolution https://trello.com/c/zsejpsDS/4335-1-sneak-peek-computed-position-off

**Comment by arski** [comment]
[(1) [Sneak Peek] Computed position off](https://trello.com/c/zsejpsDS/4335-1-sneak-peek-computed-position-off)

**Comment by arski** [comment]
@udemy/team-t hi please

**Comment by jillesme** [comment]
Can you update the version in package.json btw?

**Pull request merged**
